<?php
use Modules\BusinessLogic\Frontend as Frontend;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Braincore - front teszt site</title>

    <!-- Main CSS file -->
    <link rel="stylesheet" href="/apps/frontend/public/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/apps/frontend/public/css/owl.carousel.css" />
    <link rel="stylesheet" href="/apps/frontend/public/css/magnific-popup.css" />
    <link rel="stylesheet" href="/apps/frontend/public/css/font-awesome.css" />
    <link rel="stylesheet" href="/apps/frontend/public/css/style.css" />
    <link rel="stylesheet" href="/apps/frontend/public/css/responsive.css" />
    <link rel='stylesheet' type='text/css' href='/apps/frontend/public/css/dynamic-css.php' />

    <!-- Favicon -->
    <link rel="shortcut icon" href="/apps/frontend/public/images/icon/favicon.png">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apps/frontend/public/images/icon/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apps/frontend/public/images/icon/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apps/frontend/public/images/icon/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/apps/frontend/public/images/icon/apple-touch-icon-57-precomposed.png">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

<!-- PRELOADER -->
<div id="st-preloader">
    <div id="pre-status">
        <div class="preload-placeholder"></div>
    </div>
</div>
<!-- /PRELOADER -->


<!-- HEADER -->
<header id="header">
    <nav class="navbar st-navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#st-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="logo" href="/"><img src="/apps/frontend/public/images/logo.png" alt=""></a>
            </div>
            <?php Frontend\MenuBar::contentManager(array('MENU'))->render('menubars/menu');?>
            <!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
</header>
<!-- /HEADER -->
<!-- OUR WORKS -->
<section id="our-works">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title">
                    <h1><?=$content->title?></h1>
                    <span class="st-border"></span>
                </div>
            </div>

            <div class="portfolio-wrapper" >

                <div class="portfolio-items">
                <?php foreach ($children as $child):?>
                    <div class="col-md-4 col-sm-6 work-grid wordpress graphic">
                        <div class="portfolio-content">
                            <img class="img-responsive" style="height: 195px; " src="<?=$child->getPictures()?$child->getPictures()[0]->getUrl():''?>" alt="">
                            <div class="portfolio-overlay">
                                <a href="/apps/frontend/public/images/works/portfolio-1.jpg"><i class="fa fa-camera-retro"></i></a>
                                <h5><?=$child->title?></h5>
                                <p><?=$child->short?></p>
                            </div>
                        </div>
                    </div>
                <?php endforeach;?>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- /OUR WORKS -->

<!-- FOOTER -->
<footer id="footer">
    <div class="container">
        <div class="row">
            <!-- SOCIAL ICONS -->
            <div class="col-sm-6 col-sm-push-6 footer-social-icons">
                <span>Follow us:</span>
                <a href=""><i class="fa fa-facebook"></i></a>
                <a href=""><i class="fa fa-twitter"></i></a>
                <a href=""><i class="fa fa-google-plus"></i></a>
                <a href=""><i class="fa fa-pinterest-p"></i></a>
            </div>
            <!-- /SOCIAL ICONS -->
            <div class="col-sm-6 col-sm-pull-6 copyright">
                <p>&copy; 2015 <a href="">ShapedTheme</a>. All Rights Reserved.</p>
            </div>
        </div>
    </div>
</footer>
<!-- /FOOTER -->

<!-- Scroll-up -->
<div class="scroll-up">
    <ul><li><a href="#header"><i class="fa fa-angle-up"></i></a></li></ul>
</div>


<!-- JS -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.min.js"></script><!-- jQuery -->
<script type="text/javascript" src="/apps/frontend/public/js/bootstrap.min.js"></script><!-- Bootstrap -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.parallax.js"></script><!-- Parallax -->
<script type="text/javascript" src="/apps/frontend/public/js/smoothscroll.js"></script><!-- Smooth Scroll -->
<script type="text/javascript" src="/apps/frontend/public/js/masonry.pkgd.min.js"></script><!-- masonry -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.fitvids.js"></script><!-- fitvids -->
<script type="text/javascript" src="/apps/frontend/public/js/owl.carousel.min.js"></script><!-- Owl-Carousel -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.counterup.min.js"></script><!-- CounterUp -->
<script type="text/javascript" src="/apps/frontend/public/js/waypoints.min.js"></script><!-- CounterUp -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.isotope.min.js"></script><!-- isotope -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.magnific-popup.min.js"></script><!-- magnific-popup -->
<script type="text/javascript" src="/apps/frontend/public/js/scripts.js"></script><!-- Scripts -->


</body>
</html>